### PR TITLE
Added multi-language information and German translation

### PR DESCRIPTION
**Pull request by janklostermann**

### CODE REVIEW

**Comment by flaviocopes** [comment]
I need to check if the page title is automatically translated in Grav, in case it can be even simpler, change `title` in https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/pages/simplesearch.md to a translation string and add the translation to the plugin's languages.yaml file

**Comment by janklostermann** [comment]
Sorry, I realized that the introduction of translation was just a start, not nearly complete. I think now I have it. 
And good point of using the translation strings in the .md file, too. Done.
The pull request will come in a few minutes.

**Comment by flaviocopes** [comment]
Not sure if translating the page title is already possible, or we need to allow this possibility in Grav however. Meanwhile I added the translation for the rest of the plugin: https://github.com/getgrav/grav-plugin-simplesearch/commit/2ec4b7ec1b87b06757d444b0b5a0ad3efad65b3a

**Comment by janklostermann** [comment]
oops, seem we did some parallel work. But maybe you want to have a look anyway and merge what feels still useful.

**Comment by janklostermann** [comment]
just realized: putting the title of the simplesearch.md file in the frontmatter yaml to 

title: PLUGIN_SIMPLESEARCH.SEARCH_RESULTS

will be translate in the page itself, but not in the menu!
There it needs apparently some fixing in grav itself, as you already assumed.

**Pull request closed without merging**
